apiVersion: v1
kind: Service
metadata:
  name: cicd-app-service
spec:
  selector:
    app: cicd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort # Exposes the service on a port on each Node of the cluster
